package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXianyutypes<M extends BaseXianyutypes<M>> extends Model<M> implements IBean {

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setXianyutype(java.lang.String xianyutype) {
		set("xianyutype", xianyutype);
	}

	public java.lang.String getXianyutype() {
		return get("xianyutype");
	}

	public void setIsusing(java.lang.String isusing) {
		set("isusing", isusing);
	}

	public java.lang.String getIsusing() {
		return get("isusing");
	}

	public void setNeedMail(java.lang.String needMail) {
		set("needMail", needMail);
	}

	public java.lang.String getNeedMail() {
		return get("needMail");
	}

}
