package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXianyu1<M extends BaseXianyu1<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setTimeS(java.util.Date timeS) {
		set("timeS", timeS);
	}

	public java.util.Date getTimeS() {
		return get("timeS");
	}

	public void setHuifuNum(java.lang.Integer huifuNum) {
		set("huifuNum", huifuNum);
	}

	public java.lang.Integer getHuifuNum() {
		return get("huifuNum");
	}

	public void setCount(java.lang.Integer count) {
		set("count", count);
	}

	public java.lang.Integer getCount() {
		return get("count");
	}

	public void setSellerlevel(java.lang.String sellerlevel) {
		set("sellerlevel", sellerlevel);
	}

	public java.lang.String getSellerlevel() {
		return get("sellerlevel");
	}

	public void setPlace(java.lang.String place) {
		set("place", place);
	}

	public java.lang.String getPlace() {
		return get("place");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setSendStatus(java.lang.Integer sendStatus) {
		set("sendStatus", sendStatus);
	}

	public java.lang.Integer getSendStatus() {
		return get("sendStatus");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setIsdown(java.lang.Integer isdown) {
		set("isdown", isdown);
	}

	public java.lang.Integer getIsdown() {
		return get("isdown");
	}

	public void setNowprice(java.lang.Integer nowprice) {
		set("nowprice", nowprice);
	}

	public java.lang.Integer getNowprice() {
		return get("nowprice");
	}

	public void setPricegos(java.lang.String pricegos) {
		set("pricegos", pricegos);
	}

	public java.lang.String getPricegos() {
		return get("pricegos");
	}

	public void setXianyutype(java.lang.String xianyutype) {
		set("xianyutype", xianyutype);
	}

	public java.lang.String getXianyutype() {
		return get("xianyutype");
	}

}
