package com.demo.common.model;

import com.demo.common.model.base.BaseMybooks;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mybooks extends BaseMybooks<Mybooks> {
	public static final Mybooks dao = new Mybooks();



	/**
	 * 所有 sql 与业务逻辑写在 Model 或 Service 中，不要写在 Controller 中，养成好习惯，有利于大型项目的开发与维护
	 */
	public Page<Mybooks> paginatePage(int pageNumber, int pageSize,String bName,String bFormat) {

		String add=" where 1=1 ";
		if(bName!=null&&bName.length()>0)
			add+=" and (book_name like '%" +bName+
					"%' or tags like '%" +bName+
					"%')";

			if(bFormat!=null&&bFormat.length()>0)
				add+=" and book_format = '" +bFormat+
						"'";


		return paginate(pageNumber, pageSize, "select *", "from mybooks "+add+" order by id desc");
	}

}
