package com.demo.common.model;

import com.demo.common.model.base.BaseXianyutypes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Xianyutypes extends BaseXianyutypes<Xianyutypes> {
	public static final Xianyutypes dao = new Xianyutypes();
}
