package com.demo.common.model;

import com.demo.common.model.base.BaseXianyu;
import com.jfinal.plugin.activerecord.Page;
import com.utils.HttpclientUtil;

import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Xianyu extends BaseXianyu<Xianyu> {
	public static final Xianyu dao = new Xianyu();


	/**
	 * 所有 sql 与业务逻辑写在 Model 或 Service 中，不要写在 Controller 中，养成好习惯，有利于大型项目的开发与维护
	 */
	public Page<Xianyu> paginatePage(int pageNumber, int pageSize,String bName,String bFormat) {

		String add="where 1=1 ";

		if(bName!=null&&bName.length()>0)
			add+=" and (name like '%" +bName+
					"%')";

		if(bFormat!=null&&bFormat.length()>0)
			add+=" and (xianyutype like '%" +bFormat+
					"%')";



		return paginate(pageNumber, pageSize, "select *", "from xianyu "+add+" order by createTime desc");
	}


	public void fetchNewInfo() throws Exception {

		long t = System.currentTimeMillis();


		List<Xianyutypes> xianyutypes = Xianyutypes.dao.find("select * from xianyutypes t where t.isusing = 1");
		for (Xianyutypes xianyutype : xianyutypes) {



			String string = HttpclientUtil.get(xianyutype.getUrl());

			String wrongwords = xianyutype.getWrongwords();
			String[] wrongSpilt = null;
			if(wrongwords!=null&&wrongwords.length()>0) {
				wrongSpilt = wrongwords.split(",");
			}

			long t2 = System.currentTimeMillis();

			//去掉所有换行符
			string=string.replaceAll("\n", "");
			string=string.replaceAll("\r", "");
			//System.out.println(string);
			Pattern rePat = Pattern.compile("class=\"item-info-wrapper item-idle clearfix\".*?</li>");
			Matcher matcher = rePat.matcher(string);
			while (matcher.find()) {
				String s = matcher.group();
				String urlAll = ZkPosts.dao.getStringFromTwo(s,"item-title\">","</a></h4>",true);

				String url = ZkPosts.dao.getStringFromTwo(urlAll,"href=\"//","\">",true);



				String name = urlAll.substring(66);

				//对包含有无聊关键词的排除在外
				if(wrongSpilt!=null)
				{
					boolean wrong = false;
					for (int i = 0; i < wrongSpilt.length; i++) {
						if(name.contains(wrongSpilt[i]))
						{
							wrong = true;
							break;
						}
					}
					if(wrong) continue;
				}


				String loc = ZkPosts.dao.getStringFromTwo(s,"class=\"seller-location\">","</div>",true);
				String lev = "";//ZkPosts.dao.getStringFromTwo(s,"sh-user-vip","</span>",true).substring(18);
				String content = ZkPosts.dao.getStringFromTwo(s,"item-description\">","</div>",true);
				String price = ZkPosts.dao.getStringFromTwo(s,"</b><em>","</em>",true);
				int priceInt = -1;

				try {
					priceInt = Integer.parseInt(price.substring(0,price.lastIndexOf(".")));
				} catch (Exception e) {
					e.printStackTrace();
				}

				Xianyu xy = dao.findFirst("select * from xianyu t where t.url = '"+url+"'");
				if(xy==null)
				{
					xy = new Xianyu();
					xy.set("url",url).set("name", name).set("place", loc).set("sellerlevel", lev)
							.set("content", content).set("count",1).set("nowprice",priceInt).set("pricegos",priceInt).set("createTime", new Date()).setXianyutype(xianyutype.getName());;


					if(xianyutype.getNeedMail()!=null&&xianyutype.getNeedMail().equals("1"))
					{
						if(xianyutype.getMailMoney()==null||priceInt<=xianyutype.getMailMoney()) {
							Mail m = new Mail();
							m.setTitle( priceInt + "元-" +name  );
							m.setSendstatus(0);
							m.setContent(content + "<br>" + url);
							m.save();
						}
					}

					xy.save();
				}
				else
				{

					if(xy.getNowprice()>priceInt)
					{
						xy.set("isdown",1).set("createTime", new Date());
					}

					if(xy.getNowprice()!=priceInt)
					{
						xy.set("pricegos",priceInt+"<-"+xy.getPricegos()).setNowprice(priceInt);
						xy.set("count", xy.getCount()+1).update();
					}




				}

			}


			System.out.println("处理时间:"+(System.currentTimeMillis()-t2)+"-抓取时间："+(t2-t));


		}




	}

	public static void main(String[] args) throws Exception {

		System.out.println("sh-vip-icon0\">".length());

		dao.fetchNewInfo();
	}


}
