package com.demo.common.model;

import com.demo.common.model.base.BaseXianyu1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Xianyu1 extends BaseXianyu1<Xianyu1> {
	public static final Xianyu1 dao = new Xianyu1();
}
